spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:chatdiff}
    username: root
    password: Surexs2902@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: 1567rahulsingh@gmail.com
    password: fbixnzuqpobticcq
    properties:
      mail:
        smtp:
          trust: "*"
          starttls:
            enable: true
          auth: true
        connectiontimeout: 10000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088

razorpay:
  secretid=rzp_test_PIjtBBwswWAu4O
  secretkey=Dp5IhMqLWD7UGA6WIT9u9M3B
  threshold=10000
